detect:
  lane:
    white:
      hue_h: 20
      hue_l: 0
      lightness_h: 255
      lightness_l: 241
      saturation_h: 255
      saturation_l: 0
    yellow:
      hue_h: 20
      hue_l: 0
      lightness_h: 255
      lightness_l: 241
      saturation_h: 255
      saturation_l: 0
